version: "3.8"

services:
  db:
    image: postgres:16-alpine
    # Contournement : pas d'overlay Swarm (VXLAN) → réseau host
    network_mode: host
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    # N'écoute que sur localhost (évite d'exposer Postgres sur Internet)
    command: ["postgres", "-c", "listen_addresses=127.0.0.1"]
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  api:
    image: ghcr.io/${REGISTRY_OWNER}/mon-forum-anonyme-api:${TAG}
    network_mode: host
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: "5432"
      DB_USER: forum_user
      DB_PASSWORD_FILE: /run/secrets/postgres_password
      DB_NAME: forum
      API_PORT: "8080"
    secrets:
      - postgres_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        # En mode host, on ne peut pas binder 2 fois : stop puis start.
        order: stop-first
        parallelism: 1
        delay: 5s

  front:
    image: ghcr.io/${REGISTRY_OWNER}/mon-forum-anonyme-front:${TAG}
    network_mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        # En mode host, on ne peut pas binder 2 fois : stop puis start.
        order: stop-first
        parallelism: 1
        delay: 5s

volumes:
  postgres_data:

secrets:
  postgres_password:
    external: true

