version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  api:
    image: ghcr.io/${REGISTRY_OWNER}/mon-forum-anonyme-api:${TAG}
    environment:
      DB_HOST: tasks.db
      DB_PORT: "5432"
      DB_USER: forum_user
      DB_PASSWORD_FILE: /run/secrets/postgres_password
      DB_NAME: forum
      API_PORT: "8080"
    secrets:
      - postgres_password
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      backend_network: {}
      frontend_network:
        aliases:
          - api
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
        parallelism: 1
        delay: 5s

  front:
    image: ghcr.io/${REGISTRY_OWNER}/mon-forum-anonyme-front:${TAG}
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - frontend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
        parallelism: 1
        delay: 5s

networks:
  backend_network:
    driver: overlay
  frontend_network:
    driver: overlay

volumes:
  postgres_data:

secrets:
  postgres_password:
    external: true
